export const GET_LIST_CINEMA = "GET_LIST_CINEMA";
export const GET_MOVIE_SHOWTIMES = "GET_MOVIE_SHOWTIMES";
export const GET_INFO_CINEMA_LIST = "GET_INFO_CINEMA_LIST";
export const GET_THEATER_LIST = "GET_THEATER_LIST";
